/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.fich.calculadora;

/**
 *
 * @author Leonel Zorzoli
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelCuentaActual = new javax.swing.JLabel();
        labelResultado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonSuma = new javax.swing.JButton();
        buttonResta = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonCe = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonProducto = new javax.swing.JButton();
        buttonCociente = new javax.swing.JButton();
        buttonSalir = new javax.swing.JButton();
        buttonIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        labelCuentaActual.setForeground(new java.awt.Color(153, 153, 153));
        labelCuentaActual.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelCuentaActual.setToolTipText("");

        labelResultado.setFont(new java.awt.Font("DialogInput", 1, 48)); // NOI18N
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelResultado.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        button7.setBackground(new java.awt.Color(255, 255, 255));
        button7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button7.setText("7");
        button7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button7.setFocusPainted(false);
        button7.setPreferredSize(new java.awt.Dimension(50, 24));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(255, 255, 255));
        button8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button8.setText("8");
        button8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button8.setFocusPainted(false);
        button8.setPreferredSize(new java.awt.Dimension(50, 24));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(255, 255, 255));
        button9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button9.setText("9");
        button9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button9.setFocusPainted(false);
        button9.setPreferredSize(new java.awt.Dimension(50, 24));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonSuma.setBackground(new java.awt.Color(204, 204, 204));
        buttonSuma.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonSuma.setText("+");
        buttonSuma.setToolTipText("");
        buttonSuma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSuma.setFocusPainted(false);
        buttonSuma.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSumaActionPerformed(evt);
            }
        });

        buttonResta.setBackground(new java.awt.Color(204, 204, 204));
        buttonResta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonResta.setText("-");
        buttonResta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonResta.setFocusPainted(false);
        buttonResta.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestaActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(255, 255, 255));
        button6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button6.setText("6");
        button6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button6.setFocusPainted(false);
        button6.setPreferredSize(new java.awt.Dimension(50, 24));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(255, 255, 255));
        button5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button5.setText("5");
        button5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button5.setFocusPainted(false);
        button5.setPreferredSize(new java.awt.Dimension(50, 24));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(255, 255, 255));
        button4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button4.setText("4");
        button4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button4.setFocusPainted(false);
        button4.setPreferredSize(new java.awt.Dimension(50, 24));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 255, 255));
        button1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button1.setText("1");
        button1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button1.setFocusPainted(false);
        button1.setName("button1"); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 255, 255));
        button2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button2.setText("2");
        button2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button2.setFocusPainted(false);
        button2.setPreferredSize(new java.awt.Dimension(30, 24));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button0.setBackground(new java.awt.Color(255, 255, 255));
        button0.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button0.setText("0");
        button0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button0.setFocusPainted(false);
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonPoint.setBackground(new java.awt.Color(255, 255, 255));
        buttonPoint.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonPoint.setText(".");
        buttonPoint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonPoint.setFocusPainted(false);
        buttonPoint.setPreferredSize(new java.awt.Dimension(30, 24));
        buttonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPointActionPerformed(evt);
            }
        });

        buttonCe.setBackground(new java.awt.Color(255, 255, 255));
        buttonCe.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonCe.setText("CE");
        buttonCe.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCe.setFocusPainted(false);
        buttonCe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCeActionPerformed(evt);
            }
        });

        button3.setBackground(new java.awt.Color(255, 255, 255));
        button3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        button3.setText("3");
        button3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button3.setFocusPainted(false);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonProducto.setBackground(new java.awt.Color(204, 204, 204));
        buttonProducto.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonProducto.setText("x");
        buttonProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonProducto.setFocusPainted(false);
        buttonProducto.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductoActionPerformed(evt);
            }
        });

        buttonCociente.setBackground(new java.awt.Color(204, 204, 204));
        buttonCociente.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonCociente.setText("÷");
        buttonCociente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonCociente.setFocusPainted(false);
        buttonCociente.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonCociente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCocienteActionPerformed(evt);
            }
        });

        buttonSalir.setBackground(new java.awt.Color(153, 153, 153));
        buttonSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonSalir.setText("Salir");
        buttonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSalir.setFocusPainted(false);
        buttonSalir.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        buttonIgual.setBackground(new java.awt.Color(102, 153, 255));
        buttonIgual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        buttonIgual.setText("=");
        buttonIgual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonIgual.setFocusPainted(false);
        buttonIgual.setPreferredSize(new java.awt.Dimension(50, 24));
        buttonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttonPoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(button6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(button3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(buttonCe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(buttonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCociente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(labelCuentaActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCuentaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonResta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonCe, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );

        button1.getAccessibleContext().setAccessibleName("button1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String mostrar = "";
    String operacion = "null";
    double primerNum;
    double resultado;
    boolean activarOperacion = true;
    boolean activarPunto = true;
    boolean segundaOperacion = false;

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "7";
        } else {
            mostrar += "7";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button7ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "5";
        } else {
            mostrar += "5";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button5ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "9";
        } else {
            mostrar += "9";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button9ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "6";
        } else {
            mostrar += "6";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button6ActionPerformed

    private void buttonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPointActionPerformed
        if (activarPunto == true) {
            if (mostrar.equals("") || segundaOperacion) {
                mostrar = "0.";
            } else {
                mostrar += ".";
            }
            labelResultado.setText(mostrar);
            activarPunto = false;
            segundaOperacion = false;
        }
    }//GEN-LAST:event_buttonPointActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "1";
        } else {
            mostrar += "1";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button1ActionPerformed

    private void buttonCeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCeActionPerformed
        mostrar = "";
        labelCuentaActual.setText("");
        labelResultado.setText("0");
        operacion = "null";
        activarOperacion = true;
        activarPunto = true;
    }//GEN-LAST:event_buttonCeActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "8";
        } else {
            mostrar += "8";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button8ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "4";
        } else {
            mostrar += "4";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button4ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "2";
        } else {
            mostrar += "2";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "3";
        } else {
            mostrar += "3";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button3ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        if (labelResultado.getText().equals("0") || segundaOperacion) {
            mostrar = "0";
        } else {
            mostrar += "0";
        }
        labelResultado.setText(mostrar);
        activarOperacion = true;
        segundaOperacion = false;
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSumaActionPerformed
        if (activarOperacion == true) {
            primerNum = Double.parseDouble(mostrar);
            labelCuentaActual.setText(mostrar + " + ");
            mostrar = "";
            operacion = "sumar";

            activarOperacion = false;
        }
    }//GEN-LAST:event_buttonSumaActionPerformed

    private void buttonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestaActionPerformed
        if (activarOperacion == true) {
            primerNum = Double.parseDouble(mostrar);
            labelCuentaActual.setText(mostrar + " - ");
            mostrar = "";
            operacion = "restar";

            activarOperacion = false;
        }
    }//GEN-LAST:event_buttonRestaActionPerformed

    private void buttonProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductoActionPerformed
        if (activarOperacion == true) {
            primerNum = Double.parseDouble(mostrar);
            labelCuentaActual.setText(mostrar + " x ");
            mostrar = "";
            operacion = "multiplicar";

            activarOperacion = false;
        }
    }//GEN-LAST:event_buttonProductoActionPerformed

    private void buttonCocienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCocienteActionPerformed
        if (activarOperacion == true) {
            primerNum = Double.parseDouble(mostrar);
            labelCuentaActual.setText(mostrar + " / ");
            mostrar = "";
            operacion = "dividir";

            activarOperacion = false;
        }
    }//GEN-LAST:event_buttonCocienteActionPerformed

    private void buttonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonIgualActionPerformed
        double segundoNum;
        switch (operacion) {
            case "sumar" -> {
                segundoNum = Double.parseDouble(mostrar);
                resultado = primerNum + segundoNum;
                labelResultado.setText(String.format("% .2f", resultado));
                mostrar = String.valueOf(resultado);
                operacion = "null";
            }
            case "restar" -> {
                segundoNum = Double.parseDouble(mostrar);
                resultado = primerNum - segundoNum;
                labelResultado.setText(String.format("% .2f", resultado));
                mostrar = String.valueOf(resultado);
                operacion = "null";
            }
            case "multiplicar" -> {
                segundoNum = Double.parseDouble(mostrar);
                resultado = primerNum * segundoNum;
                labelResultado.setText(String.format("% .2f", resultado));
                mostrar = String.valueOf(resultado);
                operacion = "null";
            }
            case "dividir" -> {
                segundoNum = Double.parseDouble(mostrar);
                if (segundoNum == 0) {
                    labelResultado.setText("Error");
                } else {
                    resultado = primerNum / segundoNum;
                    labelResultado.setText(String.format("% .2f", resultado));
                    mostrar = String.valueOf(resultado);
                    operacion = "null";
                }
            }
            case "null" -> {
                labelResultado.setText(mostrar);
            }
        }

        labelCuentaActual.setText("");
        activarOperacion = true;
        activarPunto = true;

        segundaOperacion = true;

    }//GEN-LAST:event_buttonIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonCe;
    private javax.swing.JButton buttonCociente;
    private javax.swing.JButton buttonIgual;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonProducto;
    private javax.swing.JButton buttonResta;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonSuma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCuentaActual;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables

}
